### ISSUE TITLE
5.3 breaks build in webpack

### ISSUE THREAD

**Issue by fazo96** [gulpjs/glob-stream#58] opened 2015-12-19 13:01 UTC
Webpack can't build 5.3 because it has requires that are not statically evaluable in the micromatch dependency.

This commit introduced micromatch and this problem: 09f1b60e50a90806522a4072af0bd1222c0b6deb

I'm also filing an issue with micromatch :+1:

**Comment by jonschlinkert** [comment] 2015-12-19 22:26
This is a webpack problem that is caused by how webpack renames and reassigns requires (browserify does not have an issue, not does any native node.js module), but it can be resolved with a custom loader (which is totally expected in the webpack ecosystem, right?)

I think @doowb already created a custom loader for it, but if he doesn't release it and/or this continues to be a problem, we'll fix it in micromatch directly asap

**Comment by phated** [comment] 2015-12-19 22:29
@jonschlinkert I think this just needs to be fixed in micromatch. I was told there would be no breaking changes so I minor released and this is breaking us

**Comment by jonschlinkert** [comment] 2015-12-19 22:35
Fair enough, I'll push up changes to make it work with webpack. 

(fwiw, this isn't a bug in micromatch, it's a bug in webpack - but I do understand that, in effect, it looks like a bug here. I'll start doing that now)

**Comment by jonschlinkert** [comment] 2015-12-19 23:06
should be fixed. Pushed up a patch a few minutes ago

**Comment by fazo96** [comment] 2015-12-19 23:27
Thanks a lot for you efforts! :)

**Comment by doowb** [comment] 2015-12-19 23:35
I also published [unlazy loader](https://www.npmjs.com/package/unlazy-loader) that can be used in a webpack build so webpack is able to do the static analysis. Since `micromatch` was patched, this isn't necessary for your case, but I'm still posting it in case anyone else comes across this problem.

**Comment by jonschlinkert** [comment] 2015-12-19 23:50
> Thanks a lot for you efforts! :)

No problem, thanks for bringing this to our attention

**Closed** 2015-12-20 18:36 UTC

**Comment by phated** [comment] 2015-12-21 19:40
Thanks a ton @jonschlinkert - I'm going to cut a release with that version as minimum

**Comment by jonschlinkert** [comment] 2015-12-21 21:25
anytime

**Comment by Dignifiedquire** [comment] 2015-12-22 10:24
Thanks everyone for the quick turn around, really appreciated!
